import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Car Auction',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header>
                    <div className='row header-top'>
                        <div className='col-md-3 header-top-logo'>
                            <img src='img/logo.svg' />
                        </div>
                        <div className='col-md-7 header-top-search'>
                            <form>
                                <input type='text' className='header-top-search-query' placeholder='Search for vehicles by make, model, VIN, lot' />
                                <span className='header-top-search-need-help'>Need Help?</span>
                            </form>
                        </div>
                        <div className='col-md-2 header-top-login-container'>
                            <span className='header-top-login'>
                                Login
                            </span>
                            <span className='header-top-register'>
                                Register
                            </span>
                        </div>
                    </div>
                    <div className='header-nav'>
                        <div className='header-nav-menu'>
                            Home
                        </div>
                        <div className='header-nav-location'>

                        </div>
                    </div>
                </header>
                {children}
                <footer>

                </footer>
            </body>
        </html>
    )
}
